[tool.briefcase]
project_name = "/Users/frostie/projects/ORVM/my_kivy_project/bin/python /Users/frostie/projects/ORVM/OVRMKivy.py"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@example.com"

[tool.briefcase.app.usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy]
formal_name = "/Users/frostie/projects/ORVM/my_kivy_project/bin/python /Users/frostie/projects/ORVM/OVRMKivy.py"
description = "My first application"
icon = "src/usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy/resources/usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy"
sources = ['src/usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy']
requires = [
]


[tool.briefcase.app.usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.usersfrostieprojectsorvmmy_kivy_projectbinpythonusersfrostieprojectsorvmovrmkivypy.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
